ï»¿spring.application.name=StudyHub
server.port=8085

# ===============================
# C?U HÌNH DATABASE (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/StudyHub
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.charSet=UTF-8

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dangtt2004@gmail.com
spring.mail.password=czok xggr yqor moui
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
