spring.application.name=StudyHub
server.port=8085

# ===============================
# C?U HÌNH DATABASE (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/StudyHub
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.charSet=UTF-8

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dangtt2004@gmail.com
spring.mail.password=czok xggr yqor moui
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

payos.client-id=7791548f-4dc2-45b3-a96a-55180c8a7689
payos.api-key=3c1bdac4-e62d-476f-b3f9-8658ff11111d
payos.checksum-key=ef7e84843fdc75817b4ffe30b157422c4f4986b95f5ee5a3ddcf2d3c7fa5a4a7
spring.jackson.deserialization.fail-on-unknown-properties=false
